# Dockerfile para Weather
FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY AD_Weather.py /app
COPY weather_conditions.json /app

CMD ["python", "AD_Weather.py"]
